# Generated by Django 5.0 on 2024-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_remove_coordinate_result_coordinate_result_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='z_coordinate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='x_coordinate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='coordinate',
            name='y_coordinate',
            field=models.FloatField(default=0),
        ),
    ]
